"""initial clean

Revision ID: 0604abf19b5c
Revises: 
Create Date: 2026-04-10 15:48:59.515536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0604abf19b5c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('StudentAdded', sa.Column('mac_address', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'StudentAdded', ['mac_address'])
    op.alter_column('room_assignments', 'roomNo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'room_assignments', ['roomNo'])
    op.drop_constraint(op.f('room_assignments_roomNo_fkey'), 'room_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'room_assignments', 'rooms', ['roomNo'], ['roomNo'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('room_assignments_roomNo_fkey'), 'room_assignments', 'rooms', ['roomNo'], ['roomNo'])
    op.drop_constraint(None, 'room_assignments', type_='unique')
    op.alter_column('room_assignments', 'roomNo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'StudentAdded', type_='unique')
    op.drop_column('StudentAdded', 'mac_address')
    # ### end Alembic commands ###
