"""initial clean

Revision ID: 0cf0291cd9b1
Revises: 0604abf19b5c
Create Date: 2026-04-10 17:12:40.544628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cf0291cd9b1'
down_revision: Union[str, Sequence[str], None] = '0604abf19b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    
    # ✅ Step 2: Fill existing rows (IMPORTANT)
    op.execute("""
        UPDATE "StudentAdded"
        SET mac_address = id::text
        WHERE mac_address IS NULL
    """)

    # ✅ Step 3: Make it NOT NULL
    op.alter_column('StudentAdded', 'mac_address', nullable=False)

    # ✅ Step 4: Add unique constraint
    op.create_unique_constraint(None, 'StudentAdded', ['mac_address'])

    # Other existing changes
    op.alter_column('room_assignments', 'roomNo',
               existing_type=sa.VARCHAR(),
               nullable=False)

    op.create_unique_constraint(None, 'room_assignments', ['roomNo'])

    op.drop_constraint(op.f('room_assignments_roomNo_fkey'), 'room_assignments', type_='foreignkey')

    op.create_foreign_key(None, 'room_assignments', 'rooms', ['roomNo'], ['roomNo'], ondelete='CASCADE')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('room_assignments_roomNo_fkey'), 'room_assignments', 'rooms', ['roomNo'], ['roomNo'])
    op.drop_constraint(None, 'room_assignments', type_='unique')
    op.alter_column('room_assignments', 'roomNo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'StudentAdded', type_='unique')
    op.drop_column('StudentAdded', 'mac_address')
    # ### end Alembic commands ###
