"""initial clean

Revision ID: 4de76bad7176
Revises: 658828d2d68a
Create Date: 2026-04-13 17:16:51.892230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4de76bad7176'
down_revision: Union[str, Sequence[str], None] = '658828d2d68a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_calendar', sa.Column('reason', sa.String(), nullable=True))
    op.add_column('academic_calendar', sa.Column('day', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('academic_calendar', 'day')
    op.drop_column('academic_calendar', 'reason')
    # ### end Alembic commands ###
