"""initial clean

Revision ID: 658828d2d68a
Revises: 7ff07369b3ce
Create Date: 2026-04-13 15:50:19.701318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '658828d2d68a'
down_revision: Union[str, Sequence[str], None] = '7ff07369b3ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room_assignments', 'assignedBy',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('room_assignments_assignedBy_fkey'), 'room_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'room_assignments', 'AdminCreate', ['assignedBy'], ['email'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('room_assignments_assignedBy_fkey'), 'room_assignments', 'AdminCreate', ['assignedBy'], ['email'])
    op.alter_column('room_assignments', 'assignedBy',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
