"""baseline

Revision ID: 769108229798
Revises: d2aef3a2dc47
Create Date: 2025-08-15 18:04:12.555417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '769108229798'
down_revision: Union[str, Sequence[str], None] = 'd2aef3a2dc47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_foreign_key(None, 'StudentAdded', 'room_assignments', ['room_assignment_id'], ['id'])
    op.add_column('rooms', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'status')
    # op.drop_constraint(None, 'StudentAdded', type_='foreignkey')
    # ### end Alembic commands ###
