"""initial clean

Revision ID: 7ff07369b3ce
Revises: 0cf0291cd9b1
Create Date: 2026-04-13 09:35:28.413885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ff07369b3ce'
down_revision: Union[str, Sequence[str], None] = '0cf0291cd9b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_calendar',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('is_working_day', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.add_column('AdminCreate', sa.Column('branch', sa.String(), nullable=True))
    op.add_column('AdminCreate', sa.Column('year', sa.BigInteger(), nullable=True))
    op.alter_column('assistant', 'isAdmin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.add_column('leave_applications', sa.Column('current_level', sa.String(), nullable=True))
    op.add_column('leave_applications', sa.Column('coordinator_status', sa.String(), nullable=True))
    op.add_column('leave_applications', sa.Column('warden_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_applications', 'warden_status')
    op.drop_column('leave_applications', 'coordinator_status')
    op.drop_column('leave_applications', 'current_level')
    op.alter_column('assistant', 'isAdmin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('AdminCreate', 'year')
    op.drop_column('AdminCreate', 'branch')
    op.drop_table('academic_calendar')
    # ### end Alembic commands ###
