"""initial clean

Revision ID: 8335746e3496
Revises: 4de76bad7176
Create Date: 2026-04-16 11:12:36.356817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8335746e3496'
down_revision: Union[str, Sequence[str], None] = '4de76bad7176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hostels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('total_wings_per_hostel', sa.BigInteger(), nullable=True),
    sa.Column('total_floors_per_wing', sa.BigInteger(), nullable=True),
    sa.Column('total_rooms_per_floor_per_wing', sa.BigInteger(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hostels')
    # ### end Alembic commands ###
