"""initial clean

Revision ID: 8fa176c6c4d6
Revises: 8335746e3496
Create Date: 2026-04-16 11:15:35.271808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa176c6c4d6'
down_revision: Union[str, Sequence[str], None] = '8335746e3496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hostels', sa.Column('createdBy', sa.String(), nullable=False))
    op.create_foreign_key(None, 'hostels', 'AdminCreate', ['createdBy'], ['email'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hostels', type_='foreignkey')
    op.drop_column('hostels', 'createdBy')
    # ### end Alembic commands ###
