"""describe your change

Revision ID: b0a0a5d03339
Revises: 769108229798
Create Date: 2025-08-15 21:16:50.900227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0a0a5d03339'
down_revision: Union[str, Sequence[str], None] = '769108229798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_foreign_key(None, 'StudentAdded', 'room_assignments', ['room_assignment_id'], ['id'])
    # op.add_column('room_assignments', sa.Column('allocatedTo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('room_assignments', 'allocatedTo')
    # op.drop_constraint(None, 'StudentAdded', type_='foreignkey')
    # ### end Alembic commands ###
